[Resolution]
; For Resolutions above Full HD (1920x1080), please see the Readme.
xRes = 1920
yRes = 1080

[HUD]
; Place the backgrounds and HUD within a centered 4:3 rectangle
CenterHUDAndBackground = true

[Other]
; Pentium III version only: Skip the check for Intel CPU
SkipPentiumIIICheck = true
; Remove the check for game disc.
RemoveCDCheck = true
; Look for ubi.ini in the game directory rather than \Windows\UbiSoft\
MakePortable = true
; Memory allocated for TMPFixMemory and TMPLevelMemory.
; Note: Setting these to -1 will use the value spcified in Gamemem.bin instead.
TMPFixMemory = 25000000
TMPLevelMemory = 25000000
; Disable savegame snapshots. Prevents crashes at high resolutions (> Full HD),
; but makes the preview images in the savegame menu black. Please see the Readme.
DisableSaveGameSnapshots = false