[Resolution]
xRes = 1920
yRes = 1080

[HUD]
; Place the backgrounds and HUD within a centered 4:3 rectangle
CenterHUDAndBackground = true
; Remove borders around HUD (may look better when HUD is centered)
RemoveHUDBorders = false

[FPS]
; Recommended: 63 / Default: 50 / For values >66, activate PatchDeltaTiming
TargetFPS = 63
; Patch the delta timing to avoid speed-up at more than 66 FPS (EXPERIMENTAL!)
PatchDeltaTiming = false
; Fix disappearing arrows when TargetFPS > 62
DisappearingArrowFix = true

[Camera]
; Adjust vertical camera speed to facilitate aiming at high FPS
; HINT: Did you know that holding the run key also slows down camera speed?
ScaleVertCameraSpeed = 1.0

[Other]
; Remove the check for game disc.
RemoveCDCheck = true
; Look for ubi.ini in the game directory rather than \Windows\UbiSoft\
MakePortable = true
; Fix double inputs in main menu (Warning: disables in-game cheats!)
FixDoubleInputs = false
; Memory allocated for TMPFixMemory and TMPLevelMemory.
; Note: Setting these to -1 will use the value spcified in Game.mem instead.
TMPFixMemory = 25000000
TMPLevelMemory = 25000000