[Aspect Ratio]
AR = 16:9

[Other]
; Compatibility patch (needed to run the game on modern OS)
CompatibilityPatch = true
; Disable built-in 60 FPS sync / EXPERIMENTAL!
DisableInternalSync = false
; Play the game without the CD
NoCD = true
; Look for ubi.ini in the game directory rather than \Windows\UbiSoft\
MakePortable = true